name: Lunch Menu Bot

on:
  schedule:
    - cron: '50 4 * * *'  # 매일 KST 10:30
  workflow_dispatch:

jobs:
  run-lunch-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 의존성 설치
        run: npm install

      - name: Lunch Bot 실행
        run: node index.js
